# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python libpythonpro package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip and install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create false
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 .
    - name: Run Tests
      run: |
        poetry run pytest .
